  
name: node-continuous-integration

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/node/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn test